[package]
name = "proc_lexer"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
anyhow = "1.0.100"
lexer = {path = "../lexer"}
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"

[toolchain]
channel = "nightly"
